### ISSUE TITLE
代码加密了cookie怎么填啊

### ISSUE THREAD

**Issue by GGB321** [linbailo/zyqinglong#1]

**Comment by linbailo** [comment]
哪个的，用青龙变量

**Comment by GGB321** [comment]
饿了么的，请问变量是啥

**Comment by linbailo** [comment]
> 饿了么的，请问变量是啥

自行捉包把饿了么域名包里的Cookie填到elmCookie里, 多账号换行或&或@隔开
CK可以填全部或者只填SID和cookie2, 格式:
export elmCookie="SID=xxxxxxxx; cookie2=yyyyyyy;"

**Comment by linbailo** [comment]
> 饿了么的，请问变量是啥

每个脚本里面都有需要的具体东西和变量名

**Comment by GGB321** [comment]
可以截图看看你怎么弄的吗，比如你说的这个export elmCookie="SID=xxxxxxxx; cookie2=yyyyyyy;"，我知道要配置这个，但是不知道填在哪里

**Comment by linbailo** [comment]
> 



> 可以截图看看你怎么弄的吗，比如你说的这个export elmCookie="SID=xxxxxxxx; cookie2=yyyyyyy;"，我知道要配置这个，但是不知道填在哪里

打开青龙面板→环境变量→新建变量
![Uploading Screenshot_2023-06-06-11-11-04-641_com.android.browser-edit.jpg…]()

**Comment by linbailo** [comment]
![Screenshot_2023-06-06-11-11-04-641_com android browser-edit](https://github.com/linbailo/zyqinglong/assets/24869868/bce28740-68b1-48fc-a39d-efd634dfb12f)

**Comment by GGB321** [comment]
明白了，谢谢
