### ISSUE TITLE
滴滴打车没引用通知函数

### ISSUE THREAD

**Issue by iuyaa** [linbailo/zyqinglong#12]

**Comment by linbailo** [comment]
的确，没写通知函数，我不看通知，然后我就没写🌚

**Comment by iuyaa** [comment]
昨儿自己加了一下通知，结果今天没通知，发现被订阅更新了；白改🤣

然后我自己另存了加通知后的代码，就是没法和订阅同步更了😢

**Comment by linbailo** [comment]
已经更新了应用通知函数了，不过太长就可能通知不了。

**Comment by linbailo** [comment]
> 昨儿自己加了一下通知，结果今天没通知，发现被订阅更新了；白改🤣
> 
> 然后我自己另存了加通知后的代码，就是没法和订阅同步更了😢
已经更新了应用通知函数了，不过太长就可能通知不了。
可以试试

**Comment by iuyaa** [comment]
好的，感谢大佬👍👍👍
