### ISSUE TITLE
MT论坛签到无法使用与修改建议

### ISSUE THREAD

**Issue by izhuolin** [linbailo/zyqinglong#20]
mt论坛签到本无法使用 
辨别ip接口国家 中国改为 中華人民共和國 要不然无法一下步操作
![IMG_9340](https://github.com/linbailo/zyqinglong/assets/61179498/0ffd8b19-fd3f-46f4-a572-535f34e85632)

**Comment by linbailo** [comment]
> mt论坛签到本无法使用 辨别ip接口国家 中国改为 中華人民共和國 要不然无法一下步操作 ![IMG_9340](https://private-user-images.githubusercontent.com/61179498/310155290-0ffd8b19-fd3f-46f4-a572-535f34e85632.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTAyNTIsIm5iZiI6MTcwOTY4OTk1MiwicGF0aCI6Ii82MTE3OTQ5OC8zMTAxNTUyOTAtMGZmZDhiMTktZmQzZi00NmY0LWE1NzItNTM1ZjM0ZTg1NjMyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQwMTUyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTgzNTNhYjNhYWE1MGIyZjExMjgyOTAxZGRjOTAwYzdjNWZiNDZhNTZhMmY0ODU0ZDg1MzQ2YmQ4MTM5Y2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5G8cyfrNk7AtQy7EHkGlEWKOHU27WoowmfPOb6P7OAE)

今晚有空就改了

**Comment by izhuolin** [comment]
> > mt论坛签到本无法使用 辨别ip接口国家 中国改为 中華人民共和國 要不然无法一下步操作 ![IMG_9340](https://private-user-images.githubusercontent.com/61179498/310155290-0ffd8b19-fd3f-46f4-a572-535f34e85632.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTAyNTIsIm5iZiI6MTcwOTY4OTk1MiwicGF0aCI6Ii82MTE3OTQ5OC8zMTAxNTUyOTAtMGZmZDhiMTktZmQzZi00NmY0LWE1NzItNTM1ZjM0ZTg1NjMyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQwMTUyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTgzNTNhYjNhYWE1MGIyZjExMjgyOTAxZGRjOTAwYzdjNWZiNDZhNTZhMmY0ODU0ZDg1MzQ2YmQ4MTM5Y2IwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5G8cyfrNk7AtQy7EHkGlEWKOHU27WoowmfPOb6P7OAE)
> 
> 今晚有空就改了

好的 谢谢

**Comment by izhuolin** [comment]
签到报错
![Uploading IMG_9344.jpeg…]()

**Comment by linbailo** [comment]
> 签到报错 ![IMG_9344](https://private-user-images.githubusercontent.com/61179498/310501433-faafd97f-b6d5-4edf-af7b-f58f6d71aee5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjkyNTUsIm5iZiI6MTcwOTcyODk1NSwicGF0aCI6Ii82MTE3OTQ5OC8zMTA1MDE0MzMtZmFhZmQ5N2YtYjZkNS00ZWRmLWFmN2ItZjU4ZjZkNzFhZWU1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjQyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjRlZGI2Y2VkZDE2NGFlOTYyNDY4OWZhZjNlOWY0ZjJhMjg2ODVkNzZiYTAzYzBjOWQwYzIwMTc3MjJhMWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q5AxJESDvJH_QeiOOur18RkvDYDFdJ3-XfRdPClMnh8)

看看日志

**Comment by izhuolin** [comment]
> > 签到报错 ![IMG_9344](https://private-user-images.githubusercontent.com/61179498/310501433-faafd97f-b6d5-4edf-af7b-f58f6d71aee5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjkzNDksIm5iZiI6MTcwOTcyOTA0OSwicGF0aCI6Ii82MTE3OTQ5OC8zMTA1MDE0MzMtZmFhZmQ5N2YtYjZkNS00ZWRmLWFmN2ItZjU4ZjZkNzFhZWU1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjQ0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2U3YzJkNGViNGI0NzFhNTA3OTBlOTg0ODk1ODE5ZWNiNTJiMmQwN2YwM2M1OGVlNWU3MTY5MzZhYWIxNmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UJ6ZNq7WX7YOu_QcSlFtVj8EXCtIdm77x-hP697jv1s)
> 
> 看看是不是账号问题，你用账号登陆一次在试试

并不是账号问题 我正常去官网可以登入 都无需输入验证码 直接登入进去成功 这边您可以尝试看看是否与我一样报错

**Comment by linbailo** [comment]
> > > 签到报错 ![IMG_9344](https://private-user-images.githubusercontent.com/61179498/310501433-faafd97f-b6d5-4edf-af7b-f58f6d71aee5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjkzNDksIm5iZiI6MTcwOTcyOTA0OSwicGF0aCI6Ii82MTE3OTQ5OC8zMTA1MDE0MzMtZmFhZmQ5N2YtYjZkNS00ZWRmLWFmN2ItZjU4ZjZkNzFhZWU1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjQ0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2U3YzJkNGViNGI0NzFhNTA3OTBlOTg0ODk1ODE5ZWNiNTJiMmQwN2YwM2M1OGVlNWU3MTY5MzZhYWIxNmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UJ6ZNq7WX7YOu_QcSlFtVj8EXCtIdm77x-hP697jv1s)
> > 
> > 
> > 看看是不是账号问题，你用账号登陆一次在试试
> 
> 并不是账号问题 我正常去官网可以登入 都无需输入验证码 直接登入进去成功 这边您可以尝试看看是否与我一样报错

我刚刚试一下正常奥

**Comment by izhuolin** [comment]
> > > > 签到报错 ![IMG_9344](https://private-user-images.githubusercontent.com/61179498/310501433-faafd97f-b6d5-4edf-af7b-f58f6d71aee5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjkzNDksIm5iZiI6MTcwOTcyOTA0OSwicGF0aCI6Ii82MTE3OTQ5OC8zMTA1MDE0MzMtZmFhZmQ5N2YtYjZkNS00ZWRmLWFmN2ItZjU4ZjZkNzFhZWU1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjQ0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2U3YzJkNGViNGI0NzFhNTA3OTBlOTg0ODk1ODE5ZWNiNTJiMmQwN2YwM2M1OGVlNWU3MTY5MzZhYWIxNmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UJ6ZNq7WX7YOu_QcSlFtVj8EXCtIdm77x-hP697jv1s)
> > > 
> > > 
> > > 看看是不是账号问题，你用账号登陆一次在试试
> > 
> > 
> > 并不是账号问题 我正常去官网可以登入 都无需输入验证码 直接登入进去成功 这边您可以尝试看看是否与我一样报错
> 
> 我刚刚试一下正常奥

擦仂 使用您的库 就唯独这个本报错 我使用的是青龙 v2.17.2 最新版

**Comment by linbailo** [comment]
> 擦仂 使用您的库 就唯独这个本报错 我使用的是青龙 v2.17.2 最新版

获取登录码失败这个我也不知道怎么解决了
