### ISSUE TITLE
dddc.py 脚本添加 任务

### ISSUE THREAD

**Issue by chennianjie** [linbailo/zyqinglong#26]
![image](https://github.com/linbailo/zyqinglong/assets/42395916/f592f3e5-dd62-46f9-9dce-78629ee18289)

**Comment by linbailo** [comment]
> ![image](https://private-user-images.githubusercontent.com/42395916/316236298-f592f3e5-dd62-46f9-9dce-78629ee18289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjQ2NzUsIm5iZiI6MTcxMTMyNDM3NSwicGF0aCI6Ii80MjM5NTkxNi8zMTYyMzYyOTgtZjU5MmYzZTUtZGQ2Mi00NmY5LTlkY2UtNzg2MjllZTE4Mjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIzNTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NzgzNWFkNTZmNTVlMDViOTE1Zjk2MDlmMDRjYjc5NjBkYjhmMWQ1ZmQzNjQ4MjJhM2E0ZTQ2OTJkODkzYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CPo7SZ1kLlmj4CPRp409ro1lta4kZ6qKTP_2JL7J5w8)
可以看看下载到那个文件夹里面没有，然后手动添加执行任务就可以了
task 文件名字（你那里就是起始位置，直接 task 文件名字就可以了）

**Comment by linbailo** [comment]
> ![image](https://private-user-images.githubusercontent.com/42395916/316236298-f592f3e5-dd62-46f9-9dce-78629ee18289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjUwNzcsIm5iZiI6MTcxMTMyNDc3NywicGF0aCI6Ii80MjM5NTkxNi8zMTYyMzYyOTgtZjU5MmYzZTUtZGQ2Mi00NmY5LTlkY2UtNzg2MjllZTE4Mjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIzNTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5M2U4MWNhMWRjMDQ1MTY3MDMzNTRiMTdlODBmNjU1NTg2MzkzNjA5OGIwODBkYjQ0NDRmYTY2ZGRkZDI1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GX7PTYESiqal2V8FPsaJpQ32XPYXdaMQDqXSUHzdzhI)

链接错了，
https://raw.githubusercontent.com/linbailo/zyqinglong/main/dddc.py
你那个拉的是网页了，用我发的这个

**Comment by chennianjie** [comment]
thanks！
