### ISSUE TITLE
post请求失败,任务完成了，但是没自动领取

### ISSUE THREAD

**Issue by Dlian-Zero** [linbailo/zyqinglong#3]
任务完成了，但是没自动领取
账号[1]配饰会场水滴大放送 -- 可领取
post请求失败
"Response code 485 (Client Error (485))"
账号[1]新人折扣会场水滴大放送 -- 可领取
post请求失败
"Response code 485 (Client Error (485))"

**Comment by linbailo** [comment]
哪个的

**Comment by Dlian-Zero** [comment]
> 哪个的

dwnc.js

**Comment by linbailo** [comment]
> > 哪个的
> 
> dwnc.js

换一个了，环境也要换了，你看看可以没有了

**Comment by Dlian-Zero** [comment]
> > > 哪个的
> > 
> > 
> > dwnc.js
> 
> 换一个了，环境也要换了，你看看可以没有了

可以了，感谢大佬
