### ISSUE TITLE
滴滴打车脚本执行错误

### ISSUE THREAD

**Issue by letheva1** [linbailo/zyqinglong#31]
## 开始执行... 2024-04-16 12:00:00

========================

大流量卡办理：https://ehaoka.com/s/7lGSmsMR
寄快递-多家快递比价：https://kurl04.cn/7uMyfi 

========================
============📣初始化📣============
无版本更新：1.2.6
小程序版本：6.6.20
Traceback (most recent call last):
  File "/ql/data/scripts/linbailo_zyqinglong/dddc.py", line 68, in <module>
    lng,lat = os.environ.get("didijw").split("&")
    ^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

## 执行结束... 2024-04-16 12:00:06  耗时 6 秒

**Comment by linbailo** [comment]
> ## 开始执行... 2024-04-16 12:00:00
> ========================
> 
> 大流量卡办理：https://ehaoka.com/s/7lGSmsMR 寄快递-多家快递比价：https://kurl04.cn/7uMyfi
> 
> ======================== ============📣初始化📣============ 无版本更新：1.2.6 小程序版本：6.6.20 Traceback (most recent call last): File "/ql/data/scripts/linbailo_zyqinglong/dddc.py", line 68, in lng,lat = os.environ.get("didijw").split("&") ^^^^^^^ ValueError: not enough values to unpack (expected 2, got 1)
> 
> ## 执行结束... 2024-04-16 12:00:06 耗时 6 秒

 看下didijw变量

**Comment by letheva1** [comment]
好了，中间的符号没改，感谢大佬
