### ISSUE TITLE
符串tru -> 添加失败(Validation error, cannot resolve alias "all")

### ISSUE THREAD

**Issue by stayStrong007** [linbailo/zyqinglong#32]
![703840281f750222e3d9a11c852c2d0](https://github.com/linbailo/zyqinglong/assets/139205472/5caf3ec8-cdf5-47dc-9d04-c2580fe886c8)
![1f4751bde59198d43f5f82f0f6ed02c](https://github.com/linbailo/zyqinglong/assets/139205472/a309f5e0-f15e-4316-9ca6-40b0ed5eb6e3)

符串tru -> 添加失败(Validation error, cannot resolve alias "all")
我的青龙面板：2.10.13
哪位老哥知道这个是什么问题

**Comment by linbailo** [comment]
> ![703840281f750222e3d9a11c852c2d0](https://private-user-images.githubusercontent.com/139205472/324022092-5caf3ec8-cdf5-47dc-9d04-c2580fe886c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDI5MjEsIm5iZiI6MTcxMzU0MjYyMSwicGF0aCI6Ii8xMzkyMDU0NzIvMzI0MDIyMDkyLTVjYWYzZWM4LWNkZjUtNDdkYy05ZDA0LWMyNTgwZmU4ODZjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxNjAzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmRjMDVhZmY1ZjdiNWNiYmQ1YTUxMzgzMmIzZGI5YTlkOTkxOTNlZWNiYmUzYjZiYWVjYTU1YWEzNzU5NWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kig9vtM_hNhqT4y7xe_PFiOA1M1Vl9GlI1Fz9aPsCTo) ![1f4751bde59198d43f5f82f0f6ed02c](https://private-user-images.githubusercontent.com/139205472/324022277-a309f5e0-f15e-4316-9ca6-40b0ed5eb6e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDI5MjEsIm5iZiI6MTcxMzU0MjYyMSwicGF0aCI6Ii8xMzkyMDU0NzIvMzI0MDIyMjc3LWEzMDlmNWUwLWYxNWUtNDMxNi05Y2E2LTQwYjBlZDVlYjZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxNjAzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzQzYjZhMTJiMDY2ZDFiNmU3MDgwYjFiZTdmYTIzMzNlYWM5YjVjZTc1YWFjNTIxMDg5OTc1YThiMWMxZGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.27KLLCPzdg7POOmek1yViwMC2XzPVtLV6DiqPULcqYU)
> 
> 符串tru -> 添加失败(Validation error, cannot resolve alias "all") 我的青龙面板：2.10.13 哪位老哥知道这个是什么问题

链接拉错了 https://raw.githubusercontent.com/linbailo/zyqinglong/main/文件名

**Comment by stayStrong007** [comment]
> > ![703840281f750222e3d9a11c852c2d0](https://private-user-images.githubusercontent.com/139205472/324022092-5caf3ec8-cdf5-47dc-9d04-c2580fe886c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDI5MjEsIm5iZiI6MTcxMzU0MjYyMSwicGF0aCI6Ii8xMzkyMDU0NzIvMzI0MDIyMDkyLTVjYWYzZWM4LWNkZjUtNDdkYy05ZDA0LWMyNTgwZmU4ODZjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxNjAzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmRjMDVhZmY1ZjdiNWNiYmQ1YTUxMzgzMmIzZGI5YTlkOTkxOTNlZWNiYmUzYjZiYWVjYTU1YWEzNzU5NWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kig9vtM_hNhqT4y7xe_PFiOA1M1Vl9GlI1Fz9aPsCTo) ![1f4751bde59198d43f5f82f0f6ed02c](https://private-user-images.githubusercontent.com/139205472/324022277-a309f5e0-f15e-4316-9ca6-40b0ed5eb6e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDI5MjEsIm5iZiI6MTcxMzU0MjYyMSwicGF0aCI6Ii8xMzkyMDU0NzIvMzI0MDIyMjc3LWEzMDlmNWUwLWYxNWUtNDMxNi05Y2E2LTQwYjBlZDVlYjZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxNjAzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzQzYjZhMTJiMDY2ZDFiNmU3MDgwYjFiZTdmYTIzMzNlYWM5YjVjZTc1YWFjNTIxMDg5OTc1YThiMWMxZGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.27KLLCPzdg7POOmek1yViwMC2XzPVtLV6DiqPULcqYU)
> > 符串tru -> 添加失败(Validation error, cannot resolve alias "all") 我的青龙面板：2.10.13 哪位老哥知道这个是什么问题
> 
> 链接拉错了 [https://raw.githubusercontent.com/linbailo/zyqinglong/main/文件名](https://raw.githubusercontent.com/linbailo/zyqinglong/main/%E6%96%87%E4%BB%B6%E5%90%8D)

谢谢老哥，搞定了
