### ISSUE TITLE
联通运行提示版本过期

### ISSUE THREAD

**Issue by Candy-yan1** [linbailo/zyqinglong#46]
联通运行提示版本过期
![image](https://github.com/linbailo/zyqinglong/assets/66657384/47fb4bbb-b23f-4321-8a5f-4517c0542c66)

**Comment by linbailo** [comment]
> 联通运行提示版本过期 ![image](https://private-user-images.githubusercontent.com/66657384/337552573-47fb4bbb-b23f-4321-8a5f-4517c0542c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzExODYsIm5iZiI6MTcxNzc3MDg4NiwicGF0aCI6Ii82NjY1NzM4NC8zMzc1NTI1NzMtNDdmYjRiYmItYjIzZi00MzIxLThhNWYtNDUxN2MwNTQyYzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE0MzQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OTY3MmQ5NWJhNjEwMzdhNWQzYzk5MDdkNGQzMDZlNGRhZjg1YjAzOGNhNjU5ZmU0YjlhYzljZDgzN2EyMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v1HenAaIQ5cxLDQmcYa8yxMUlS7_h35PYvvKKn62Ql8)

更新了
