### ISSUE TITLE
滴滴打车

### ISSUE THREAD

**Issue by kyo77** [linbailo/zyqinglong#58]
============📣初始化📣============
无版本更新：1.2.6
小程序版本：6.6.20
Traceback (most recent call last):
  File "dddc.py", line 68, in <module>
    lng,lat = os.environ.get("didijw").split("&")
ValueError: not enough values to unpack (expected 2, got 1)
不知道是什么情况

**Comment by linbailo** [comment]
> ============📣初始化📣============ 无版本更新：1.2.6 小程序版本：6.6.20 Traceback (most recent call last): File "dddc.py", line 68, in lng,lat = os.environ.get("didijw").split("&") ValueError: not enough values to unpack (expected 2, got 1) 不知道是什么情况

看下变量didijw

**Comment by kyo77** [comment]
> > ============📣初始化📣============ 无版本更新：1.2.6 小程序版本：6.6.20 Traceback (most recent call last): File "dddc.py", line 68, in lng,lat = os.environ.get("didijw").split("&") ValueError: not enough values to unpack (expected 2, got 1) 不知道是什么情况
> 
> 
> 
> 看下变量didijw

添加了didijw，然后也还是提示这个

**Comment by xubillde** [comment]
game开头的接口在哪个模块里面？没找到哎

**Comment by xubillde** [comment]
找到了
