### ISSUE TITLE
滴滴打车大佬的删库了，本库的py脚本报登录失败

### ISSUE THREAD

**Issue by wyxiong431** [linbailo/zyqinglong#65]
滴滴打车大佬的删库了，本库的py脚本报登录失败，请问大家能用吗

**Comment by linbailo** [comment]
> 滴滴打车大佬的删库了，本库的py脚本报登录失败，请问大家能用吗

看看报错

**Comment by Beigec** [comment]
删库之后很多脚本都用不了了

**Comment by wyxiong431** [comment]
> > 滴滴打车大佬的删库了，本库的py脚本报登录失败，请问大家能用吗
> 
> 看看报错

![20240718](https://github.com/user-attachments/assets/1395f4b6-9002-4fe7-81b6-c7eff0ecccd0)

**Comment by wyxiong431** [comment]
请大佬修复

**Comment by linbailo** [comment]
> 请大佬修复

重新抓看看，我目前8给账号都正常

**Comment by wyxiong431** [comment]
> > 请大佬修复
> 
> 重新抓看看，我目前8给账号都正常

重新抓可以了，谢谢大佬
