### ISSUE TITLE
大佬，请问海底捞脚本报这个错是什么原因，谢谢

### ISSUE THREAD

**Issue by wyxiong431** [linbailo/zyqinglong#71]
## 开始执行... 2024-08-22 23:29:08

========================
小错误
========================
查找到1个账号
登录第1个账号
----------------------
未知错误
xxxxxxxxxxxx

## 执行结束... 2024-08-22 23:29:09 耗时 1 秒

**Comment by linbailo** [comment]
> ## 开始执行... 2024-08-22 23:29:08
> # ========================
> 小错误
> ## 查找到1个账号
> 登录第1个账号
> 未知错误 xxxxxxxxxxxx
> 
> ## 执行结束... 2024-08-22 23:29:09 耗时 1 秒

登录有问题，ck是不是错了

**Comment by wyxiong431** [comment]
CK应该没问题，格式是这样吗？TOKEN_APP_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX，请问前面报“小错误”是什么原因？

**Comment by linbailo** [comment]
> CK应该没问题，格式是这样吗？TOKEN_APP_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX，请问前面报“小错误”是什么原因？

可以的话ck发我试试

**Comment by wyxiong431** [comment]
请大佬帮忙试试
TOKEN_APP_c434bff5-6d78-4ab7-8cfc-082da33dc9fa




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linbailo/zyqinglong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月23日(星期五) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linbailo/zyqinglong] 大佬，请问海底捞脚本报这个错是什么原因，谢谢 (Issue #71)





  
CK应该没问题，格式是这样吗？TOKEN_APP_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX，请问前面报“小错误”是什么原因？
  
可以的话ck发我试试

**Comment by wyxiong431** [comment]
谢谢，已发邮件

**Comment by wyxiong431** [comment]
已解决，运行正常，谢谢大佬
