### ISSUE TITLE
霸王茶几 签到提示 业务繁忙,请稍后再试

### ISSUE THREAD

**Issue by huzi068** [linbailo/zyqinglong#75]
新抓token还是这个错误

![image](https://github.com/user-attachments/assets/1629fc3c-ae5a-41c7-ac9b-ef65b8e0f0bd)

**Comment by zhangyining215** [comment]
好像是霸王茶姬那边换接口了，等看谁更新把

**Comment by linbailo** [comment]
尽力了，反编译不出来小程序，有个加密了

**Comment by zhangyining215** [comment]
那就是彻底没救了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月31日(周六) 晚上7:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [linbailo/zyqinglong] 霸王茶几 签到提示 业务繁忙,请稍后再试 (Issue #75)




 
尽力了，反编译不出来小程序，有个加密了

**Comment by checkToke** [comment]
https://github.com/checkToke/yangtai  这里面的霸王茶几可以用
