### ISSUE TITLE
滴滴报错

### ISSUE THREAD

**Issue by sunshinev** [linbailo/zyqinglong#9]
requests.exceptions.SSLError: HTTPSConnectionPool(host='rewards.xiaojukeji.com', port=443): Max retries exceeded with url: /loyalty_credit/bonus/getWelfareUsage4Wallet?token=X1DqAxzq5rNcpMPLLHSMNd-yfJiuaSxaGEyCcjjkTuaUye1LV3koz4UpkYSFWPq_v-7IQvtdNuP0xq3XH7gTJe9euOidDeBzsk9DtFwAA__8=&city_id=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))

## 执行结束... 2023-11-30 17:35:32  耗时 1 秒

**Comment by linbailo** [comment]
> requests.exceptions.SSLError: HTTPSConnectionPool(host='rewards.xiaojukeji.com', port=443): Max retries exceeded with url: /loyalty_credit/bonus/getWelfareUsage4Wallet?token=X1DqAxzq5rNcpMPLLHSMNd-yfJiuaSxaGEyCcjjkTuaUye1LV3koz4UpkYSFWPq_v-7IQvtdNuP0xq3XH7gTJe9euOidDeBzsk9DtFwAA__8=&city_id=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))
> 
> ## 执行结束... 2023-11-30 17:35:32 耗时 1 秒

目前正常，在试试
