### ISSUE TITLE
dddc.py代码中包含压缩的代码，用于获取并打开无关的推广链接

### ISSUE THREAD

**Issue by z1n8tjshh** [linbailo/zyqinglong#98]
dddc.py代码中包含: 
`exec(marshal.loads(zlib.decompress(b'x\x9c\x8dR\xc1n\xd3@\x14\xac\xc4\t……')))
`

代码中包含压缩的代码，其中包含一个lincsh()函数
```
def lincsh():
    myprint('========================')
    try:
        m = requests.get(url='https://sharechain.qq.com/edfa0ceafb21e98a1cfc47d7551e637d')
        m1 = re.findall('lin公告(.*?)公告lin',m.text)
        if 'href=' in m1[1]:
                myprint(m1[0].replace(r"\\n","\n"))
        elif 'href=' in m1[0]:
                myprint(m1[1].replace(r"\\n","\n"))
    except Exception as e:
        myprint('小错误')
    myprint('========================')
lincsh()
```

代码作用是:
打开链接: https://sharechain.qq.com/edfa0ceafb21e98a1cfc47d7551e637d
获取并展示推广链接: lin公告寄快递来：………………\n\n官方大流量卡：[…………\n\n无广告免费去水印小程序《…………》公告lin`

**Comment by linbailo** [comment]
原来库被封了，气死我了，只能这样调用了，还不行，后面有时间在看看其他东西了

**Comment by z1n8tjshh** [comment]
这段就是单纯的推广链接呀，对功能的执行没有什么作用，是刻意加上的吗？

**Comment by linbailo** [comment]
> 这段就是单纯的推广链接呀，对功能的执行没有什么作用，是刻意加上的吗？

打下小广告，这个还是检查是否有版本更新
